using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Mafia.Generators.Content;

[Generator]
public class ContentFactoryGenerator : IIncrementalGenerator
{
    private const string STAT_INTERFACE = "Mafia.Core.Ecs.Components.Interfaces.IStatComponent";
    private const string RELATION_INTERFACE = "Mafia.Core.Ecs.Relations.Interfaces.IRelation";
    private const string DISABLE_REASON_INTERFACE = "Mafia.Core.Ecs.Components.State.IDisableReason";
    private const string TAG_INTERFACE = "Mafia.Core.Ecs.Components.Tags.ITag";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var types = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsStructWithBaseList(node),
                transform: static (ctx, _) => GetTypeInfo(ctx))
            .Where(static info => info is not null)
            .Select(static (info, _) => info!.Value);

        var collected = types.Collect();

        context.RegisterSourceOutput(collected, static (spc, types) =>
        {
            var stats = types.Where(t => t.Category == TypeCategory.Stat).ToList();
            var relations = types.Where(t => t.Category == TypeCategory.Relation).ToList();
            var disableReasons = types.Where(t => t.Category == TypeCategory.DisableReason).ToList();
            var tags = types.Where(t => t.Category == TypeCategory.Tag).ToList();

            spc.AddSource("EffectFactory.g.cs", GenerateEffectFactory(stats, relations, disableReasons, tags));
            spc.AddSource("ConditionFactory.g.cs", GenerateConditionFactory(stats, relations, tags));
        });
    }

    private static bool IsStructWithBaseList(SyntaxNode node)
    {
        return node switch
        {
            StructDeclarationSyntax { BaseList.Types.Count: > 0 } => true,
            RecordDeclarationSyntax { ClassOrStructKeyword.Text: "struct", BaseList.Types.Count: > 0 } => true,
            _ => false
        };
    }

    private static DiscoveredType? GetTypeInfo(GeneratorSyntaxContext context)
    {
        var structDecl = (TypeDeclarationSyntax)context.Node;
        if (context.SemanticModel.GetDeclaredSymbol(structDecl) is not INamedTypeSymbol symbol)
            return null;

        TypeCategory? category = null;

        foreach (var iface in symbol.AllInterfaces)
        {
            var name = iface.ToDisplayString();
            if (name == STAT_INTERFACE) category = TypeCategory.Stat;
            else if (name == RELATION_INTERFACE) category = TypeCategory.Relation;
            else if (name == DISABLE_REASON_INTERFACE) category = TypeCategory.DisableReason;
            else if (name == TAG_INTERFACE) category = TypeCategory.Tag;
        }

        if (category is null)
            return null;

        return new DiscoveredType(
            symbol.Name,
            symbol.ContainingNamespace.ToDisplayString(),
            category.Value);
    }

    private static string Normalize(string name)
    {
        return name.ToLowerInvariant();
    }

    private static string GenerateEffectFactory(
        List<DiscoveredType> stats,
        List<DiscoveredType> relations,
        List<DiscoveredType> disableReasons,
        List<DiscoveredType> tags)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Mafia.Core.Events.Effects;");
        sb.AppendLine("using Mafia.Core.Events.Effects.Interfaces;");

        AppendUsings(sb, stats, relations, disableReasons, tags);

        sb.AppendLine();
        sb.AppendLine("namespace Mafia.Core.Content.Factories;");
        sb.AppendLine();
        sb.AppendLine("public partial class EffectFactory");
        sb.AppendLine("{");

        // ResolveModifyStat
        GenerateSwitchMethod(sb, "ResolveModifyStat", "IEventEffect", stats,
            "string normalizedStat, string path, int amount",
            t => $"new ModifyStat<{t.TypeName}>(path, amount)",
            "normalizedStat", "stat");

        // ResolveSetStat
        GenerateSwitchMethod(sb, "ResolveSetStat", "IEventEffect", stats,
            "string normalizedStat, string path, int value",
            t => $"new SetStat<{t.TypeName}>(path, value)",
            "normalizedStat", "stat");

        // ResolveAddTag
        GenerateSwitchMethod(sb, "ResolveAddTag", "IEventEffect", tags,
            "string normalizedTag, string path",
            t => $"new AddTag<{t.TypeName}>(path)",
            "normalizedTag", "tag",
            "new AddCustomTag(normalizedTag, path)");

        // ResolveRemoveTag
        GenerateSwitchMethod(sb, "ResolveRemoveTag", "IEventEffect", tags,
            "string normalizedTag, string path",
            t => $"new RemoveTag<{t.TypeName}>(path)",
            "normalizedTag", "tag",
            "new RemoveCustomTag(normalizedTag, path)");

        // ResolveAddRelationship
        GenerateSwitchMethod(sb, "ResolveAddRelationship", "IEventEffect", relations,
            "string normalizedKind, string fromPath, string toPath",
            t => $"new AddRelationship<{t.TypeName}>(fromPath, toPath)",
            "normalizedKind", "relation kind");

        // ResolveRemoveRelationship
        GenerateSwitchMethod(sb, "ResolveRemoveRelationship", "IEventEffect", relations,
            "string normalizedKind, string fromPath, string toPath",
            t => $"new RemoveRelationship<{t.TypeName}>(fromPath, toPath)",
            "normalizedKind", "relation kind");

        // ResolveDisableCharacter
        GenerateSwitchMethod(sb, "ResolveDisableCharacter", "IEventEffect", disableReasons,
            "string normalizedReason, string path",
            t => $"new DisableCharacter<{t.TypeName}>(path)",
            "normalizedReason", "disable reason");

        // ResolveEnableCharacter
        GenerateSwitchMethod(sb, "ResolveEnableCharacter", "IEventEffect", disableReasons,
            "string normalizedReason, string path",
            t => $"new EnableCharacter<{t.TypeName}>(path)",
            "normalizedReason", "disable reason");

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string GenerateConditionFactory(
        List<DiscoveredType> stats,
        List<DiscoveredType> relations,
        List<DiscoveredType> tags)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Mafia.Core.Events.Conditions;");
        sb.AppendLine("using Mafia.Core.Events.Conditions.Interfaces;");

        AppendUsings(sb, stats, relations, new List<DiscoveredType>(), tags);

        sb.AppendLine();
        sb.AppendLine("namespace Mafia.Core.Content.Factories;");
        sb.AppendLine();
        sb.AppendLine("public partial class ConditionFactory");
        sb.AppendLine("{");

        // ResolveStatThreshold
        GenerateSwitchMethod(sb, "ResolveStatThreshold", "IEventCondition", stats,
            "string normalizedStat, string path, Comparison comparison, int value",
            t => $"new StatThreshold<{t.TypeName}>(path, comparison, value)",
            "normalizedStat", "stat");

        // ResolveHasTagCondition
        GenerateSwitchMethod(sb, "ResolveHasTagCondition", "IEventCondition", tags,
            "string normalizedTag, string path",
            t => $"new HasTagCondition<{t.TypeName}>(path)",
            "normalizedTag", "tag",
            "new HasCustomTag(normalizedTag, path)");

        // ResolveHasRelationship
        GenerateSwitchMethod(sb, "ResolveHasRelationship", "IEventCondition", relations,
            "string normalizedKind, string fromPath, string toPath",
            t => $"new HasRelationship<{t.TypeName}>(fromPath, toPath)",
            "normalizedKind", "relation kind");

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void GenerateSwitchMethod(
        StringBuilder sb,
        string methodName,
        string returnType,
        List<DiscoveredType> types,
        string parameters,
        System.Func<DiscoveredType, string> constructorCall,
        string switchVariable,
        string errorLabel,
        string? fallbackExpression = null)
    {
        sb.AppendLine($"    private static {returnType} {methodName}({parameters})");
        sb.AppendLine("    {");
        sb.AppendLine($"        return {switchVariable} switch");
        sb.AppendLine("        {");
        foreach (var t in types)
            sb.AppendLine($"            \"{Normalize(t.TypeName)}\" => {constructorCall(t)},");
        if (fallbackExpression is not null)
            sb.AppendLine($"            _ => {fallbackExpression}");
        else
            sb.AppendLine($"            _ => throw new System.ArgumentException($\"Unknown {errorLabel}: '{{{switchVariable}}}'\")");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void AppendUsings(StringBuilder sb, params List<DiscoveredType>[] typeLists)
    {
        var namespaces = new HashSet<string>();
        foreach (var list in typeLists)
        foreach (var t in list)
            namespaces.Add(t.Namespace);
        foreach (var ns in namespaces.OrderBy(n => n))
            sb.AppendLine($"using {ns};");
    }

    private enum TypeCategory
    {
        Stat,
        Relation,
        DisableReason,
        Tag
    }

    private readonly struct DiscoveredType
    {
        public string TypeName { get; }
        public string Namespace { get; }
        public TypeCategory Category { get; }

        public DiscoveredType(string typeName, string ns, TypeCategory category)
        {
            TypeName = typeName;
            Namespace = ns;
            Category = category;
        }
    }
}
