using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Mafia.Generators.Context;

[Generator]
public class RelationRegistryGenerator : IIncrementalGenerator
{
    private const string RELATION_FULL_NAME = "Mafia.Core.Ecs.Relations.Interfaces.IRelation";
    private const string FAMILY_RELATION_FULL_NAME = "Mafia.Core.Ecs.Relations.Interfaces.IFamilyRelation";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var relations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsStructWithBaseList(node),
                transform: static (ctx, _) => GetRelationInfo(ctx))
            .Where(static info => info is not null)
            .Select(static (info, _) => info!.Value);

        var collected = relations.Collect();

        context.RegisterSourceOutput(collected, static (spc, relations) =>
        {
            spc.AddSource("EntityScope.RelationRegistry.g.cs", GenerateEntityScopeSource(relations));
            spc.AddSource("RelationQueries.g.cs", GenerateRelationQueriesSource(relations));
        });
    }

    private static bool IsStructWithBaseList(SyntaxNode node)
    {
        return node is StructDeclarationSyntax { BaseList.Types.Count: > 0 };
    }

    private static RelationInfo? GetRelationInfo(GeneratorSyntaxContext context)
    {
        var structDecl = (StructDeclarationSyntax)context.Node;
        if (context.SemanticModel.GetDeclaredSymbol(structDecl) is not INamedTypeSymbol symbol)
            return null;

        var isRelation = false;
        var isFamily = false;

        foreach (var iface in symbol.AllInterfaces)
        {
            var name = iface.ToDisplayString();
            if (name == RELATION_FULL_NAME)
                isRelation = true;
            if (name == FAMILY_RELATION_FULL_NAME)
                isFamily = true;
        }

        if (!isRelation)
            return null;

        return new RelationInfo(
            symbol.Name,
            symbol.ContainingNamespace.ToDisplayString(),
            isFamily);
    }

    private static string GenerateEntityScopeSource(ImmutableArray<RelationInfo> relations)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using fennecs;");
        sb.AppendLine("using Mafia.Core.Ecs.Relations.Interfaces;");

        var namespaces = new HashSet<string>();
        foreach (var r in relations)
            namespaces.Add(r.Namespace);
        foreach (var ns in namespaces)
            sb.AppendLine($"using {ns};");

        sb.AppendLine();
        sb.AppendLine("namespace Mafia.Core.Context;");
        sb.AppendLine();
        sb.AppendLine("public sealed partial class EntityScope");
        sb.AppendLine("{");

        // FollowRelation switch
        sb.AppendLine("    private static Entity? FollowRelation(Entity? from, ReadOnlySpan<char> relationName)");
        sb.AppendLine("    {");
        sb.AppendLine("        return relationName switch");
        sb.AppendLine("        {");
        foreach (var r in relations)
            sb.AppendLine($"            \"{r.TypeName}\" => GetRelationTarget<{r.TypeName}>(from),");
        sb.AppendLine("            _ => null");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();

        // GetRelationTarget helper
        sb.AppendLine("    private static Entity? GetRelationTarget<TRelation>(Entity? from)");
        sb.AppendLine("        where TRelation : struct, IRelation");
        sb.AppendLine("    {");
        sb.AppendLine("        if (from is not { } entity) return null;");
        sb.AppendLine("        var targets = entity.Get<TRelation>(Match.Entity);");
        sb.AppendLine("        if (targets.Length == 0) return null;");
        sb.AppendLine("        return targets[0].Target;");
        sb.AppendLine("    }");

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string GenerateRelationQueriesSource(ImmutableArray<RelationInfo> relations)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using fennecs;");
        sb.AppendLine("using Mafia.Core.Ecs.Relations.Interfaces;");

        var namespaces = new HashSet<string>();
        foreach (var r in relations)
            namespaces.Add(r.Namespace);
        foreach (var ns in namespaces)
            sb.AppendLine($"using {ns};");

        sb.AppendLine();
        sb.AppendLine("namespace Mafia.Core.Ecs.Relations;");
        sb.AppendLine();
        sb.AppendLine("public static partial class RelationQueries");
        sb.AppendLine("{");

        // CollectTargets<T> generic single-type collection
        sb.AppendLine("    public static List<Entity> CollectTargets<TRelation>(Entity entity)");
        sb.AppendLine("        where TRelation : struct, IRelation");
        sb.AppendLine("    {");
        sb.AppendLine("        var targets = new List<Entity>();");
        sb.AppendLine("        var relations = entity.Get<TRelation>(Match.Entity);");
        sb.AppendLine("        for (var i = 0; i < relations.Length; i++)");
        sb.AppendLine("            targets.Add(relations[i].Target);");
        sb.AppendLine("        return targets;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // CollectFamilyTargets all IFamilyRelation types
        sb.AppendLine("    public static List<Entity> CollectFamilyTargets(Entity entity)");
        sb.AppendLine("    {");
        sb.AppendLine("        var targets = new List<Entity>();");
        foreach (var r in relations)
        {
            if (r.IsFamily)
                sb.AppendLine($"        AddTargets<{r.TypeName}>(entity, targets);");
        }
        sb.AppendLine("        return targets;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Private helper
        sb.AppendLine("    private static void AddTargets<TRelation>(Entity entity, List<Entity> targets)");
        sb.AppendLine("        where TRelation : struct, IRelation");
        sb.AppendLine("    {");
        sb.AppendLine("        var relations = entity.Get<TRelation>(Match.Entity);");
        sb.AppendLine("        for (var i = 0; i < relations.Length; i++)");
        sb.AppendLine("            targets.Add(relations[i].Target);");
        sb.AppendLine("    }");

        sb.AppendLine("}");
        return sb.ToString();
    }

    private readonly struct RelationInfo
    {
        public string TypeName { get; }
        public string Namespace { get; }
        public bool IsFamily { get; }

        public RelationInfo(string typeName, string ns, bool isFamily)
        {
            TypeName = typeName;
            Namespace = ns;
            IsFamily = isFamily;
        }
    }
}
