using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Mafia.Generators.Context;

[Generator]
public class RelationRegistryGenerator : IIncrementalGenerator
{
    private const string RELATION_FULL_NAME = "Mafia.Core.Ecs.Relations.Interfaces.IRelation";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var relations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsStructWithBaseList(node),
                transform: static (ctx, _) => GetRelationInfo(ctx))
            .Where(static info => info is not null)
            .Select(static (info, _) => info!.Value);

        var collected = relations.Collect();

        context.RegisterSourceOutput(collected, static (spc, relations) =>
        {
            var source = GenerateSource(relations);
            spc.AddSource("EntityScope.RelationRegistry.g.cs", source);
        });
    }

    private static bool IsStructWithBaseList(SyntaxNode node)
    {
        return node is StructDeclarationSyntax { BaseList.Types.Count: > 0 };
    }

    private static RelationInfo? GetRelationInfo(GeneratorSyntaxContext context)
    {
        var structDecl = (StructDeclarationSyntax)context.Node;
        if (context.SemanticModel.GetDeclaredSymbol(structDecl) is not INamedTypeSymbol symbol)
            return null;

        foreach (var iface in symbol.AllInterfaces)
        {
            if (iface.ToDisplayString() == RELATION_FULL_NAME)
            {
                return new RelationInfo(
                    symbol.Name,
                    symbol.ContainingNamespace.ToDisplayString());
            }
        }

        return null;
    }

    private static string GenerateSource(ImmutableArray<RelationInfo> relations)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using fennecs;");
        sb.AppendLine("using Mafia.Core.Ecs.Relations.Interfaces;");

        // Collect distinct namespaces from relations
        var namespaces = new HashSet<string>();
        foreach (var r in relations)
            namespaces.Add(r.Namespace);

        foreach (var ns in namespaces)
            sb.AppendLine($"using {ns};");

        sb.AppendLine();
        sb.AppendLine("namespace Mafia.Core.Context;");
        sb.AppendLine();
        sb.AppendLine("public sealed partial class EntityScope");
        sb.AppendLine("{");

        // FollowRelation switch
        sb.AppendLine("    private static Entity? FollowRelation(Entity? from, ReadOnlySpan<char> relationName)");
        sb.AppendLine("    {");
        sb.AppendLine("        return relationName switch");
        sb.AppendLine("        {");

        foreach (var r in relations)
            sb.AppendLine($"            \"{r.TypeName}\" => GetRelationTarget<{r.TypeName}>(from),");

        sb.AppendLine("            _ => null");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();

        // GetRelationTarget helper
        sb.AppendLine("    private static Entity? GetRelationTarget<TRelation>(Entity? from)");
        sb.AppendLine("        where TRelation : struct, IRelation");
        sb.AppendLine("    {");
        sb.AppendLine("        if (from is not { } entity) return null;");
        sb.AppendLine("        var targets = entity.Get<TRelation>(Match.Entity);");
        sb.AppendLine("        if (targets.Length == 0) return null;");
        sb.AppendLine("        return targets[0].Target;");
        sb.AppendLine("    }");

        sb.AppendLine("}");

        return sb.ToString();
    }

    private readonly struct RelationInfo
    {
        public string TypeName { get; }
        public string Namespace { get; }

        public RelationInfo(string typeName, string ns)
        {
            TypeName = typeName;
            Namespace = ns;
        }
    }
}
